name: "PR workflow"
on:
  pull_request:
    branches:
      - "v3-dev"
jobs:
  build:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      # - uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pre-commit/
      #     key: ${{ hashFiles('.pre-commit-config.yaml') }}

      # - name: Run pre-commit
      #   run: uv run pre-commit run --all-files

      - name: Minimize uv cache
        run: uv cache prune --ci
